version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        RUN_TESTS: "false"
    ports:
      - "5230:80"
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=db;Database=StockAlertsDb;User Id=sa;Password=P@ssw0rd92;Encrypt=False;TrustServerCertificate=True
      - ASPNETCORE_URLS=http://+:80
    restart: always

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "P@ssw0rd92"
      ACCEPT_EULA: "Y"
    ports:
      - "14330:1433"
    volumes:
      - sqlvolume:/var/opt/mssql

volumes:
  sqlvolume:
